### ISSUE TITLE
Tests and TS are failing locally :(

### ISSUE THREAD

**Issue by mkraenz** [mkraenz/teatime#10]
Two weeks ago everything was fine. CICD also says everything is fine. But my local I get both type errors on `nx tsc daily-questions` as well as test failures 

```log
 FAIL   daily-questions  src/settings/SettingsButtonRow.spec.tsx
        ● Test suite failed to run
      
          TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')
      
          > 1 | import { render } from '@testing-library/react-native';
              | ^
            2 | import { noop } from 'lodash';
            3 | import SettingsButtonRow from './SettingsButtonRow';
            4 |
      
            at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:494:46
            at Object.<anonymous> (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:18680:5)
            at Object.<anonymous> (node_modules/react-test-renderer/index.js:6:20)
            at Object.<anonymous> (node_modules/@testing-library/react-native/src/act.ts:3:1)
            at Object.<anonymous> (node_modules/@testing-library/react-native/src/pure.ts:1:1)
            at Object.<anonymous> (node_modules/@testing-library/react-native/src/index.ts:1:1)
            at Object.<anonymous> (src/settings/SettingsButtonRow.spec.tsx:1:1)
      
      Test Suites: 1 failed, 2 passed, 3 total
```

`yarn --frozen-lockfile` does not fix it. Clearing nx cache and node_modules neither.

## AC

- [ ] local setup is working again
- [ ] app builds again

**Comment by mkraenz** [comment]
Seems to have been a bad leftover lib version within node_modules of `apps/daily-questions` that badly interacted with the root level node_modules. Plus some more weirdness. see commit message
